on:
  push:
    branches:
      - main

  workflow_dispatch:

name: codecov

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v5

      - name: Install package
        run: python -m pip install .

      - name: Install coverage
        run: python -m pip install coverage

      - name: Unit tests
        run: tests/run_tests.sh -c

      - name: Coveralls
        uses: coverallsapp/github-action@v2
